# -*- coding: utf-8 -*-
"""
Created on Thu Dec 11 01:03:12 2025

@author: toora
"""

followers = [
  {"name": "Instagram", "followers": 697, "description": "Social media platform", "country": "United States"},
  {"name": "Cristiano Ronaldo", "followers": 668, "description": "Footballer", "country": "Portugal"},
  {"name": "Lionel Messi", "followers": 510, "description": "Footballer", "country": "Argentina"},
  {"name": "Selena Gomez", "followers": 416, "description": "Musician and actress", "country": "United States"},
  {"name": "Kylie Jenner", "followers": 391, "description": "Media personality", "country": "United States"},
  {"name": "Dwayne Johnson", "followers": 391, "description": "Actor and professional wrestler", "country": "United States"},
  {"name": "Ariana Grande", "followers": 373, "description": "Musician and actress", "country": "United States"},
  {"name": "Kim Kardashian", "followers": 354, "description": "Media personality", "country": "United States"},
  {"name": "Beyoncé", "followers": 308, "description": "Musician and actress", "country": "United States"},
  {"name": "Khloé Kardashian", "followers": 300, "description": "Media personality", "country": "United States"},
  {"name": "Nike", "followers": 298, "description": "Sportswear brand", "country": "United States"},
  {"name": "Justin Bieber", "followers": 292, "description": "Musician", "country": "Canada"},
  {"name": "Kendall Jenner", "followers": 285, "description": "Media personality", "country": "United States"},
  {"name": "Taylor Swift", "followers": 281, "description": "Musician", "country": "United States"},
  {"name": "National Geographic", "followers": 276, "description": "Magazine / Media", "country": "United States"},
  {"name": "Virat Kohli", "followers": 274, "description": "Cricketer", "country": "India"},
  {"name": "Jennifer Lopez", "followers": 247, "description": "Musician and actress", "country": "United States"},
  {"name": "Neymar", "followers": 231, "description": "Footballer", "country": "Brazil"},
  {"name": "Kourtney Kardashian", "followers": 216, "description": "Media personality", "country": "United States"},
  {"name": "Miley Cyrus", "followers": 211, "description": "Musician and actress", "country": "United States"},
  {"name": "Katy Perry", "followers": 202, "description": "Musician", "country": "United States"},
  {"name": "Real Madrid CF", "followers": 180, "description": "Football club", "country": "Spain"},
  {"name": "Zendaya", "followers": 176, "description": "Actress and singer", "country": "United States"},
  {"name": "Kevin Hart", "followers": 176, "description": "Comedian and actor", "country": "United States"},
  {"name": "Cardi B", "followers": 163, "description": "Musician and actress", "country": "United States"},
  {"name": "LeBron James", "followers": 158, "description": "Basketball player", "country": "United States"},
  {"name": "Demi Lovato", "followers": 152, "description": "Musician and actress", "country": "United States"},
  {"name": "Rihanna", "followers": 149, "description": "Musician", "country": "Barbados"},
  {"name": "FC Barcelona", "followers": 145, "description": "Football club", "country": "Spain"},
  {"name": "Chris Brown", "followers": 144, "description": "Musician", "country": "United States"},
  {"name": "Drake", "followers": 142, "description": "Musician", "country": "Canada"},
  {"name": "Ellen DeGeneres", "followers": 134, "description": "Comedian and television host", "country": "United States"},
  {"name": "Kylian Mbappé", "followers": 128, "description": "Footballer", "country": "France"},
  {"name": "Billie Eilish", "followers": 124, "description": "Musician", "country": "United States"},
  {"name": "UEFA Champions League", "followers": 121, "description": "Sports competition", "country": "Europe"},
  {"name": "Lisa", "followers": 106, "description": "Musician", "country": "Thailand"},
  {"name": "Gal Gadot", "followers": 106, "description": "Actress", "country": "Israel"},
  {"name": "Vin Diesel", "followers": 104, "description": "Actor", "country": "United States"},
  {"name": "Narendra Modi", "followers": 99.2, "description": "Politician", "country": "India"},
  {"name": "NASA", "followers": 97.2, "description": "Space agency", "country": "United States"},
  {"name": "Shraddha Kapoor", "followers": 94.9, "description": "Actress", "country": "India"},
  {"name": "Shakira", "followers": 94.3, "description": "Musician", "country": "Colombia"},
  {"name": "Priyanka Chopra", "followers": 93.6, "description": "Actress", "country": "India"},
  {"name": "NBA", "followers": 90.4, "description": "Basketball league", "country": "United States"},
  {"name": "Dua Lipa", "followers": 88.7, "description": "Musician", "country": "United Kingdom"},
  {"name": "Snoop Dogg", "followers": 88.6, "description": "Musician", "country": "United States"},
  {"name": "Jennie", "followers": 88.5, "description": "Musician", "country": "South Korea"},
  {"name": "David Beckham", "followers": 88.4, "description": "Footballer", "country": "United Kingdom"},
  {"name": "Alia Bhatt", "followers": 86.6, "description": "Actress", "country": "India"},
  {"name": "Rosé", "followers": 84.3, "description": "Musician", "country": "New Zealand"}
]

youtube_subscribed = [
  {"name": "MrBeast", "subscribers_millions": 454, "category": "Entertainment", "country": "United States"},
  {"name": "T‑Series", "subscribers_millions": 308, "category": "Music", "country": "India"},
  {"name": "Cocomelon - Nursery Rhymes", "subscribers_millions": 199, "category": "Education", "country": "United States"},
  {"name": "SET India", "subscribers_millions": 188, "category": "Entertainment", "country": "India"},
  {"name": "Vlad and Niki", "subscribers_millions": 148, "category": "Entertainment", "country": "United States / Russia"},
  {"name": "Kids Diana Show", "subscribers_millions": 137, "category": "Entertainment", "country": "United States / Ukraine"},
  {"name": "Stokes Twins", "subscribers_millions": 133, "category": "Entertainment", "country": "United States"},
  {"name": "Like Nastya", "subscribers_millions": 131, "category": "Entertainment", "country": "United States / Russia"},
  {"name": "KIMPRO", "subscribers_millions": 126, "category": "Entertainment", "country": "South Korea"},
  {"name": "Zee Music Company", "subscribers_millions": 121, "category": "Music", "country": "India"},
  {"name": "WWE", "subscribers_millions": 111, "category": "Sports", "country": "United States"},
  {"name": "PewDiePie", "subscribers_millions": 110, "category": "Entertainment", "country": "Sweden / United States"},
  {"name": "Goldmines", "subscribers_millions": 108, "category": "Film / Entertainment", "country": "India"},
  {"name": "Sony SAB", "subscribers_millions": 104, "category": "Entertainment", "country": "India"},
  {"name": "BLACKPINK", "subscribers_millions": 99.4, "category": "Music", "country": "South Korea"},
  {"name": "ChuChu TV Nursery Rhymes & Kids Songs", "subscribers_millions": 97.9, "category": "Education / Kids", "country": "India"},
  {"name": "Alan's Universe", "subscribers_millions": 96.9, "category": "Entertainment", "country": "United States"},
  {"name": "Zee TV", "subscribers_millions": 95.4, "category": "Entertainment", "country": "India"},
  {"name": "Alejo Igoa", "subscribers_millions": 93.6, "category": "Entertainment", "country": "Argentina"},
  {"name": "A4", "subscribers_millions": 90.7, "category": "Entertainment", "country": "Belarus"},
  {"name": "Pinkfong", "subscribers_millions": 83.4, "category": "Education / Kids", "country": "South Korea"},
  {"name": "BANGTANTV", "subscribers_millions": 81.5, "category": "Music", "country": "South Korea"},
  {"name": "Colors TV", "subscribers_millions": 81.3, "category": "Entertainment", "country": "India"},
  {"name": "5‑Minute Crafts", "subscribers_millions": 81.0, "category": "How-to / DIY", "country": "Cyprus / International"},
  {"name": "ZAMZAM ELECTRONICS TRADING", "subscribers_millions": 80.8, "category": "Entertainment", "country": "United Arab Emirates"},
  {"name": "T‑Series Bhakti Sagar", "subscribers_millions": 80.6, "category": "Music", "country": "India"},
  {"name": "Toys and Colors", "subscribers_millions": 80.3, "category": "Entertainment / Kids", "country": "United States"},
  {"name": "Tips Official", "subscribers_millions": 79.4, "category": "Entertainment / Music", "country": "India"},
  {"name": "Topper Guild", "subscribers_millions": 79.2, "category": "Entertainment", "country": "United States"},
  {"name": "HYBE LABELS", "subscribers_millions": 78.8, "category": "Music", "country": "South Korea"},
  {"name": "KL BRO Biju Rithvik", "subscribers_millions": 78.4, "category": "Lifestyle / Vlogs", "country": "India"},
  {"name": "UR · Cristiano", "subscribers_millions": 76.9, "category": "Entertainment / Sports", "country": "Portugal"},
  {"name": "Justin Bieber", "subscribers_millions": 76.4, "category": "Music", "country": "Canada"},
  {"name": "Aaj Tak", "subscribers_millions": 73.8, "category": "News", "country": "India"},
  {"name": "Shemaroo Filmi Gaane", "subscribers_millions": 73.7, "category": "Music", "country": "India"},
  {"name": "Infobells - Hindi", "subscribers_millions": 71.6, "category": "Education / Kids", "country": "India"},
  {"name": "Mark Rober", "subscribers_millions": 71.6, "category": "Education / Entertainment", "country": "United States"},
  {"name": "HAR PAL GEO", "subscribers_millions": 70.4, "category": "Entertainment", "country": "Pakistan"},
  {"name": "El Reino Infantil", "subscribers_millions": 70.3, "category": "Music / Kids", "country": "Argentina"},
  {"name": "Fede Vigevani", "subscribers_millions": 70.2, "category": "Entertainment", "country": "Mexico"},
  {"name": "YRF", "subscribers_millions": 70.1, "category": "Music", "country": "India"},
  {"name": "Sony Music India", "subscribers_millions": 68.6, "category": "Music", "country": "India"},
  {"name": "ISSEI / いっせい", "subscribers_millions": 68.4, "category": "Entertainment", "country": "Japan"},
  {"name": "Canal KondZilla", "subscribers_millions": 67.9, "category": "Music", "country": "Brazil"},
  {"name": "Wave Music", "subscribers_millions": 67.9, "category": "Music", "country": "India"},
  {"name": "Eminem Music", "subscribers_millions": 66.0, "category": "Music", "country": "United States"},
  {"name": "ARY Digital HD", "subscribers_millions": 65.9, "category": "Entertainment", "country": "Pakistan"}
]

